Repository cse110-fa22-group23/cse110-fa22-group23, pull requests merged in 2022-11, with the labels that each got.

#49 Add pitch pdf
  specs/pitch/Project Pitch.pdf
Labels: documentation

#53 added new backend adrs
  specs/adr/adr-application-storage-loc.md
  specs/adr/adr-features.md
  specs/adr/adr-storage-structure.md
Labels: documentation

#94 Improve codeclimate issues
  .config/jsdoc.conf.json
  source/assets/css/modal.css
  source/assets/js/index.js
  source/out/global.html
  source/out/index.html
  source/out/index.js.html
  source/package.json
Labels: bug

#102 fix minor sort by column bug
  source/assets/js/index.js
  source/out/index.js.html
Labels: bug

#104 added new branding to index.html and other relevant img files
  source/assets/images/branding/Logo_Vertical.PNG
  source/assets/images/branding/Logo_horizontal.PNG
  source/assets/images/branding/Name.PNG
  source/assets/images/branding/Name_bold.PNG
  source/assets/images/branding/favicon.ico
  source/index.html
Labels: enhancement

#138 126 page caching fix
  source/sw.js
Labels: bug
